import "./globals.css";
import type { Metadata } from "next";
// import { Inter } from 'next/font/google'
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Mayu Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <div className="dark:bg-black">
        <Navbar />
        <div className="pt-20">{children}</div>
      </div>
    </html>
  );
}
